site_name: nomad-nomad-dtu-nanolab-plugin
site_description: A plugin for the schemas, parsers,
site_author: Lena Mittman

repo_url: https://github.com/DTU-Nanolab-materials-discovery/nomad-nomad-dtu-nanolab-plugin

nav:
  - Home: index.md
  - Tutorial: tutorial/tutorial.md
  - How-to guides:
      - Install this Plugin: how_to/install_this_plugin.md
      - Use this Plugin: how_to/use_this_plugin.md
      - Contribute to this plugin: how_to/contribute_to_this_plugin.md
      - Contribute to the documentation: how_to/contribute_to_the_documentation.md
  - Explanation: explanation/explanation.md
  - Reference:
      - Overview: reference/index.md
      - Lab Inventory & Items:
          - Samples and Libraries: reference/samples.md
          - Substrates: reference/substrates.md
          - Targets: reference/targets.md
          - Gas Supplies: reference/gas.md
          - Instruments: reference/instruments.md
      - Synthesis & Processing:
          - Sputtering Deposition: reference/sputtering.md
          - Rapid Thermal Processing: reference/rtp.md
          - Thermal Evaporation: reference/thermal.md
          - Library Cleaving: reference/cleaving.md
      - Characterization:
          - Base Measurement Infrastructure: reference/basesections.md
          - X-ray Diffraction (XRD): reference/xrd.md
          - X-ray Photoelectron Spectroscopy (XPS): reference/xps.md
          - Energy-Dispersive X-ray (EDX): reference/edx.md
          - Photoluminescence (PL): reference/pl.md
          - Ellipsometry: reference/ellipsometry.md
          - Raman Spectroscopy: reference/raman.md
          - RT Measurements: reference/rt.md
      - Data Analysis:
          - Jupyter Analysis: reference/analysis.md
plugins:
  - search
  - glightbox
  - macros:
      module_name: docs/main
theme:
  name: material
  palette:
    primary: "#2A4CDF"
    accent: "#008A67"
  font:
    text: "Titillium Web"
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.path
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
